name: scribble
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  http: ^1.3.0
  web_socket_channel: ^3.0.2
  equatable: ^2.0.7
  uuid: ^4.5.1
  path_provider: ^2.1.5
  http_parser: ^4.1.2
  flutter_colorpicker: ^1.1.0
  shared_preferences: ^2.5.2
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  lottie: ^3.3.1
  perfect_freehand: ^2.3.2
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true